-- -- Creation DB
-- CREATE DATABASE IF NOT EXISTS fortify;
--
-- -- Users
-- CREATE TABLE IF NOT EXISTS users
-- (
--     username VARCHAR(200) NOT NULL PRIMARY KEY,
--     password VARCHAR(500) NOT NULL,
--     enabled BOOLEAN NOT NULL
--     );
--
-- -- Authority
-- CREATE TABLE IF NOT EXISTS authorities
-- (
--     username VARCHAR(200) NOT NULL,
--     authority VARCHAR(50) NOT NULL,
--     CONSTRAINT fk_authorities_users FOREIGN KEY (username) REFERENCES users (username),
--     CONSTRAINT username_authority UNIQUE (username, authority)
--     );
